version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: challengedt
      MYSQL_USER: challengedt
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin.root
    ports:
      - 33060:3306
    volumes:
      - /mysql:/var/lib/mysql
    networks:
      - backend
      
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - backend

networks:
  backend: